name: Build MySQL 5.7.44 RPM for ARM on CentOS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ARM CentOS environment
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker pull --platform linux/arm64 hxsoong/kylin:v10-sp3

      - name: Build MySQL RPM for ARM on CentOS
        run: |
          docker run --rm --platform linux/arm64 -v $(pwd):/workspace -w /workspace hxsoong/kylin:v10-sp3 /bin/bash -c "
          set -e
          yum -y update &&
          yum clean all &&
          yum install -y cmake gcc gcc-c++ libaio-devel ncurses-devel bison wget git make openssl-devel &&
          mkdir mysql-5.7.44 &&
          cd mysql-5.7.44 &&
          wget https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.44.tar.gz &&
          tar -xzf mysql-5.7.44.tar.gz &&
          cd mysql-5.7.44 &&
          cmake . -DDOWNLOAD_BOOST=1 -DWITH_BOOST=./boost -DWITH_SSL=system &&
          make &&
          make package &&
          cp *.rpm /workspace
          "

      - name: Upload RPM to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: mysql-5.7.44-arm64.rpm
          path: "*.rpm"
